### ISSUE TITLE
[Roadmap][Epic] จัดทำ Page Roadmap ภาษาไทย

### ISSUE THREAD

**Issue by sikiryl** [ThaiProgrammer/tpa#20]
### Requirements
* จัดทำ Page Roadmap โดยมีตัวอย่างจาก https://roadmap.sh/
* ให้ Fork / Clone มาทำเป็นของ TPA เอง [Github Link](https://github.com/kamranahmedse/developer-roadmap)
* แปลเป็นภาษาไทย

### Example
* image.png
* image.png

### Resources
* https://roadmap.sh/
* https://exercism.org/
* https://github.com/kamranahmedse/developer-roadmap

**Comment by ponggun** [comment]
- [ ] แผนสองถ้า Deploy บน Azure - Ponggun ได้นะครับ

**Comment by sikiryl** [comment]
สรุปกันย้ายไปใช้ https://github.com/ThaiProgrammer/tpa-path
